PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# every pmd resource needs a description
SELECT ?a ?l WHERE {
    values ?t {owl:Class owl:ObjectProperty owl:DatatypeProperty}
    ?a rdf:type ?t .
    ?a rdfs:label ?l . 
    FILTER REGEX (str(?a), "w3id.org/pmd/co", "i") .
    OPTIONAL {
       ?a <http://www.w3.org/2004/02/skos/core#definition> ?d .
    }
   FILTER (!BOUND(?d))

}
