name: MAKE

on:
  push:
    branches:
    - main
jobs:
  make:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: ODK refesh imports #We need to create pmdco.ttl as the shapes-library depends on it.
      run: |
           cd src/ontology/
           make refresh-imports pmdco.ttl
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' #optional defaults to master
